name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22

          script: |
            cd /var/www/bkcarreracademy

            git pull origin main

            echo "=== BUILDING FRONTEND ==="
            cd frontend
            npm install
            npm run build

            echo "=== RESTARTING BACKEND ==="
            cd ../backend
            npm install
            pm2 restart all
            pm2 save

            sudo systemctl restart nginx
